CREATE database data_analysis_project;

			-- Business Insights Questions

-- 1. Which category generates highest revenue?

select category,round(sum(purchase_amount),2) as highest_revenue
from customer_behaviour_analysis
group by category
order by highest_revenue desc;

-- ? Business problem:- Company doesn't know which category contributes most to revenue.

-- Impact:-
		-- Helps prioritize high performing category
    -- Optimizes inventory planning
    -- Improves marketing ROI
------------------------------------------------------------------------------------------------

-- 2. Are discounts actually increasing purchase value ?

select discount_applied,
round(sum(purchase_amount),2) as total_revenue,
round(avg(purchase_amount),2) as avg_revenue
from customer_behaviour_analysis
group by discount_applied;

-- ? Business Problem:- Discounts may reduce profits without increasing sales.

-- Impact:-
		-- Identify effectiveness of discounts
    -- Reduce unnecessary discount costs
    -- Improve profit margin
--------------------------------------------------------------------------------------------------

-- 3. What is the total revenue generated by male and female customer?

select gender,
round(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by gender
order by total_revenue desc;

-- ? Business Problem:- Lack of understanding of revenue contribution by gender segments.

-- Impact:-	
		-- Helps design targeted marketing campaigns
    -- Improves customer sementation strategy
    -- Enhances personalization efforts
---------------------------------------------------------------------------------------------------

-- 4. Which customer used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount,discount_applied
from customer_behaviour_analysis
where discount_applied='Yes' and
purchase_amount > (select avg(purchase_amount) from customer_behaviour_analysis)
limit 10;

-- ? Business problem:- Company cannot identifying high-spending customers who are also discount users

-- Impact:-
		-- 1. Identifying premium discount-sensitive customers
    -- 2. Enables targeted discount compaigns
    -- 3. Improves customer retention and revenue
	
-------------------------------------------------------------------------------------------------

-- 5. Which are the top/bottom 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as avg_rating
from customer_behaviour_analysis
group by item_purchased
order by avg_rating desc limit 5;

select item_purchased,round(avg(review_rating),2) as avg_rating
from customer_behaviour_analysis
group by item_purchased
order by avg_rating limit 5;

-- ? Business Problem:- No visibility into product performance based on customer satisfaction.

-- Impact:-
		-- 1.Promotes high performing products.
    -- 2.Improve low rated product.
    -- 3.Enhance customer experience.
	
-------------------------------------------------------------------------------------------------

-- 6. Average purchase: Standard vs Express shipping.

select shipping_type,
count(distinct customer_id) as order_placed,
round(avg(purchase_amount),2) as avg_purchase
from customer_behaviour_analysis
where shipping_type in ('Standard','Express')
group by shipping_type;

-- ? Business Problem:-Unclear if faster shipping leads to higher spending.

-- Impact:-
		-- 1.Helps optimizing shipping pricing strategy.
    -- 2.Encourages premium shipping adoption.
    -- 3.Increases average shipping value.
	
----------------------------------------------------------------------------------------

-- 7. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
count(customer_id) as users,
round(avg(purchase_amount),2) as avg_revenue,
round(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by subscription_status
order by total_revenue desc;

-- ? Business Problem:- The effectiveness of subscription programs is unknown.

-- Impact:- 
		-- 1.Validates subscription model performance.
    -- 2.Improves customer loyality programs.
    -- 3.Increases customer lifetime value (CLV).
	
------------------------------------------------------------------------------------------------------

-- 8. Top 5 products with highest discount usage %.

select item_purchased,
count(item_purchased) as total_item_sold,
count(case when discount_applied='Yes' then 1 end) as item_sold_after_discount,
count(case when discount_applied='Yes' then 1 end) * 100 / count(*) as discount_percent
from customer_behaviour_analysis
group by item_purchased
order by discount_percent desc
limit 5;

-- ? Business Problem:-Some products may be overly dependent on discount.

-- Impact:-
		-- 1.Identifies discount-driven products.
    -- 2.Helps optimizing pricing strategy.
    -- 3.Reduces profit margin loss.
        
---------------------------------------------------------------------------------------------------

-- 9. Segement customer into new,returning and loyal based on their total number of previos purchase,
-- and show the count of each segment.

select 
case when previous_purchases='0' then 'new_customer'
	 when previous_purchases between 1 and 15 then 'returning_customer'
     else 'loyal_customer' end as customer_segment,
count(*) as customer_count
from customer_behaviour_analysis
group by case 
when previous_purchases='0' then 'new_customer'
when previous_purchases between 1 and 15 then 'returning_customer'
else 'loyal_customer'
end;

-- ? Business Problem:- Lack of customer segmentation leads to generic strategies.

-- Impact:-
		-- 1.Enables personalized marketing
    -- 2.Improves retention strategies
    -- 3.Increases conversion rates.
	
----------------------------------------------------------------------------------------------------

-- 10. What are the top 3 most purchased products within each category?

with cte as (
select category,item_purchased,
count(item_purchased) as most_purchased,
rank() over(partition by category order by count(item_purchased) desc) as rnk
from customer_behaviour_analysis
group by category,item_purchased
)
select * from cte
where rnk < 3;


-- ? Business Problem:- The company doesn't know top performing products within categories.

-- Impact:-
		-- 1.Improves product placement and recommendation
    -- 2.Helps inventory optimization
    -- 3.Increases sales through best seller
        
-------------------------------------------------------------------------------------------------

-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select case
when previous_purchases > 5 then 'Repeat Buyers'
else 'Normal Buyers'
end as customer_type,
subscription_status,
count(*) as customer_count,
count(*) * 100 / sum(count(*))
over(partition by  case
when previous_purchases > 5 then 'Repeat Buyers'
else 'Normal Buyers' end) as percent
from customer_behaviour_analysis
group by 
case
when previous_purchases > 5 then 'Repeat Buyers'
else 'Normal Buyers'
end,subscription_status;

-- ? Business Problem:- Unclear relationship between loyality and subscription.

-- Impact:-
		-- 1.Improves subscription targetting
    -- 2.Increases conversion to paid program
    -- 3.Increase customer retention strategy
	
------------------------------------------------------------------------------------------------

-- 12. What is the revenue contribution of each age group?

select case 
when age between 18 and 25 then '18-25'
when age between 26 and 35 then '26-35'
when age between 36 and 50 then '36-50'
else '51+'
end as age_group,
round(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by case 
when age between 18 and 25 then '18-25'
when age between 26 and 35 then '26-35'
when age between 36 and 50 then '36-50'
else '51+'
end
order by total_revenue desc;

-- ? Business Problem:- No visibility into which age group contributes most to revenue.

-- Impact:-
		-- 1.Enables age based-targetting
    -- 2.Enhances marketting efficiency
	
---------------------------------------------------------------------------------------------------





